version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379